#!/usr/bin/env node
/**
 * build-shaders.mjs — resolve #include in shaders/src/* (via the frontend-forge
 * bundle.mjs resolver) and emit scene/shaders.js as ES-module string exports.
 * The page has no bundler, so shaders are prebuilt and committed.
 *   node tools/build-shaders.mjs
 */
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleShader } from "./bundle.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "shaders/src");
const out = ["// GENERATED by tools/build-shaders.mjs — do not edit. Sources: shaders/src, shaders/lib.\n"];
for (const f of readdirSync(src).sort()) {
  const glsl = bundleShader(join(src, f));
  if (/#include/.test(glsl)) throw new Error(`unresolved #include in ${f}`);
  const name = basename(f).replace(/\.(frag|vert)$/, (m) => (m === ".frag" ? "Frag" : "Vert"));
  out.push(`export const ${name} = ${JSON.stringify(glsl)};\n`);
}
out.push(`export const screenVert = ${JSON.stringify(bundleShader(join(root, "shaders/lib/common/screen.vert")))};\n`);
writeFileSync(join(root, "scene/shaders.js"), out.join("\n"));
console.log("wrote scene/shaders.js");
